# Generated by Django 5.1.1 on 2024-11-02 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('department', models.CharField(choices=[('HR', 'Human Resources'), ('Engineering', 'Engineering'), ('Sales', 'Sales')], max_length=100)),
                ('role', models.CharField(choices=[('Manager', 'Manager'), ('Developer', 'Developer'), ('Analyst', 'Analyst')], max_length=100)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
